# Generated by Django 5.0.6 on 2024-06-14 12:52

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.IntegerField(blank=True, choices=[(1, 'Каждый день'), (2, 'Через день'), (3, 'Раз в три дня'), (4, 'Раз в четыре дня'), (5, 'Раз в пять дней'), (6, 'Раз в шесть дней'), (7, 'Раз в неделю')], default=1, null=True, verbose_name='Периодичность')),
                ('treat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
